### ISSUE TITLE
Season metadata not saved to NFO file

### ISSUE THREAD

**Issue by Soitora** [ZeroQI/Lambda.bundle#27] opened 2021-03-29 06:11 UTC
Season metadata is not saved, this includes season title and season description.

**Comment by ZeroQI** [comment] 2021-03-29 07:48
Duplicate of https://github.com/ZeroQI/Lambda.bundle/issues/28

**Closed as completed by ZeroQI** 2021-03-29 07:48 UTC

**Comment by Soitora** [comment] 2021-03-29 08:08
I created them seperately as I don't feel that it's a duplicate

The fields that's mentioned in #28 is under the `<art>` category
