### ISSUE TITLE
Feature Request: Actors

### ISSUE THREAD

**Issue by Dalarialus** [ZeroQI/Lambda.bundle#37] opened 2021-12-13 03:02 UTC
Hello! Would it be possible to have Lambda export actor names/art as well? Thanks!

**Comment by ZeroQI** [comment] 2021-12-13 07:28
Lines 407 (Movies) and 474 (Series) already export actors though...
Cannot reproduce currently as NAS down and no free time so assistance would be appreciated

**Comment by ZeroQI** [comment] 2022-01-29 14:02
No update from bug report creator, closing

**Closed as completed by ZeroQI** 2022-01-29 14:02 UTC
